List<List<String>> webs = [
  [
    'https://izidos.com/',
    'https://jut.su',
    'https://vk.com',
  ],
  [
    'https://ru.wikipedia.org/wiki/Заглавная_страница',
    'https://www.google.ru/',
  ],
  [
    'https://www.facebook.com',
    'https://m.youtube.com/@user-yp9ew4hx6h',
  ],
  [
    'https://www.apple.com',
    'https://m.youtube.com/@GRAVEMINDunderground',
  ],
];
