List<List<String>> webs = [
  [
    'https://dzen.ru/a/Y3o2pu6-6HnloGjY',
    'https://jut.su',
    'https://vk.com',
  ],
  [
    'https://ru.wikipedia.org/wiki/Заглавная_страница',
    'https://www.google.ru/',
  ],
  [
    'https://dzen.ru/a/Y3o2pu6-6HnloGjY',
    'https://m.youtube.com/@user-yp9ew4hx6h',
  ],
  [
    'https://dzen.ru/a/Y3o2pu6-6HnloGjY',
    'https://m.youtube.com/@GRAVEMINDunderground',
  ],
];
